
name: Delete all hub/vwan networking components

# only trigger on pull request closed events
on:
  schedule: 
    - cron: '* 00 * * *'
  workflow_dispatch: {}

permissions:
      id-token: write
      contents: read

env:
  Location: "norwayeast"
  hubSubscriptionId: "cef889d1-be0e-48d3-ab41-6a15291a2d95"
  hubResourceGroup: "hubnw-connectivity"
  hubSpokeSubscriptionId: "3b6e398c-8e14-47b5-952b-f201880f9746"
  hubSpokeResourceGroup: "hubnw-norwayeast-spoke-networking"
  hubManagementGroup: "hubnw"
  vwanSubscriptionId: "b520e36b-23a2-4c14-a04f-854dc0c24ee1"
  vwanResourceGroup: "vwan-connectivity"
  vwanSpokeSubscriptionId: "328c153d-e17a-43f1-85fa-26295930711d"
  vwanSpokeResourceGroup: "vwan-norwayeast-spoke-networking"
  vwanManagementGroup: "vwan"

  
jobs:
  delete_hub_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

    - name: Az CLI Delete Hub Network
      id: delete_hub_network
      shell: bash
      run: |
          az account set --subscription ${{ env.hubSubscriptionId }}
          az group delete --name ${{ env.hubResourceGroup }} --yes
      continue-on-error: true
    
    - name: Az CLI Delete Hub spoke Network
      id: delete_hub_spoke_network
      shell: bash
      run: |
          az account set --subscription ${{ env.hubSpokeSubscriptionId }}
          az group delete --name ${{ env.hubSpokeResourceGroup }} --yes
      continue-on-error: true

    - name: Delete Hub/spoke monitor policy assignments
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $excludelist = @('Deploy-ASC-Monitoring',
          'Deploy-AzActivity-Log',
          'Deploy-MDFC-Config',
          'Deploy-Resource-Diag',
          'Deploy-VM-Monitoring',
          'Deploy-VMSS-Monitoring')
          Get-AzPolicyAssignment -Scope /providers/Microsoft.Management/managementGroups/${{ env.hubManagementGroup }} | where {$psitem.name -notin $excludelist} | foreach {Remove-AzPolicyAssignment -Id $PSItem.PolicyAssignmentId}
        azPSVersion: "latest"

    - name: Delete Hub/spoke monitor policy definitions
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Get-AzPolicyDefinition -ManagementGroupName hubnw | where {$PSItem.Properties.Metadata.source -eq 'https://github.com/Azure/ALZ-Monitor/'} | foreach {Remove-AzPolicyDefinition -Id $PSItem.ResourceId -Force}
        azPSVersion: "latest"

  delete_vwan_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

    - name: Az CLI Delete vWAN Network
      id: delete_vwan_network
      shell: bash
      run: |
          az account set --subscription ${{ env.vwanSubscriptionId }}
          az group delete --name ${{ env.vwanResourceGroup }} --yes
      continue-on-error: true

    - name: Az CLI Delete vwan spoke Network
      id: delete_vwan_spoke_network
      shell: bash
      run: |
          az account set --subscription ${{ env.vwanSpokeSubscriptionId }}
          az group delete --name ${{ env.vwanSpokeResourceGroup }} --yes
      continue-on-error: true