name: Delete all hub/vwan networking components

# only trigger on pull request closed events
on:
  schedule:
    - cron: "* 00 * * *"
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  Location: "norwayeast"
  hubSubscription: "hub-connectivity"
  hubResourceGroup: "hubnw-connectivity"
  hubSpokeSubscription: "hub-landing zone"
  hubSpokeResourceGroup: "hubnw-norwayeast-spoke-networking"
  hubManagementGroup: "hubnw"
  vwanSubscription: "vwan-connectivity"
  vwanResourceGroup: "vwan-connectivity"
  vwanSpokeSubscription: "vwan-landing zone"
  vwanSpokeResourceGroup: "vwan-norwayeast-spoke-networking"
  vwanManagementGroup: "vwan"

jobs:
  delete_hub_job:
    runs-on: ubuntu-latest
    #environment: deploy

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Delete hubnw management group deployments
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzManagementGroupDeployment -ManagementGroupId ${{ env.hubManagementGroup }} | Remove-AzManagementGroupDeployment -AsJob
          azPSVersion: "latest"

      - name: Az CLI Delete Hub Network
        id: delete_hub_network
        shell: bash
        run: |
          az account set --name ${{ env.hubSubscription }}
          az group delete --name ${{ env.hubResourceGroup }} --yes
        continue-on-error: true

      - name: Az CLI Delete Hub spoke Network
        id: delete_hub_spoke_network
        shell: bash
        run: |
          az account set --name ${{ env.hubSpokeSubscription }}
          az group delete --name ${{ env.hubSpokeResourceGroup }} --yes
        continue-on-error: true

      - name: Delete Hub/spoke monitor policy assignments
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzPolicyAssignment -Scope /providers/Microsoft.Management/managementGroups/hubnw | foreach {Remove-AzPolicyAssignment -Id $PSItem.PolicyAssignmentId}
            Get-AzPolicyAssignment -Scope /providers/Microsoft.Management/managementGroups/hubnw-platform-identity | foreach {Remove-AzPolicyAssignment -Id $PSItem.PolicyAssignmentId}
            Get-AzPolicyAssignment -Scope /providers/Microsoft.Management/managementGroups/hubnw-platform-connectivity | foreach {Remove-AzPolicyAssignment -Id $PSItem.PolicyAssignmentId}
            Get-AzPolicyAssignment -Scope /providers/Microsoft.Management/managementGroups/hubnw-platform-management | foreach {Remove-AzPolicyAssignment -Id $PSItem.PolicyAssignmentId}
            Get-AzPolicyAssignment -Scope /providers/Microsoft.Management/managementGroups/hubnw-landingzones | foreach {Remove-AzPolicyAssignment -Id $PSItem.PolicyAssignmentId}
          azPSVersion: "latest"

      - name: Delete Hub/spoke monitor policy Initiatives
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzPolicySetDefinition -ManagementGroupName ${{ env.hubManagementGroup }} | where {$PSItem.Properties.Metadata.source -eq 'https://github.com/Azure/ALZ-Monitor/'} | foreach {Remove-AzPolicySetDefinition -Id $PSItem.ResourceId -Force}
          azPSVersion: "latest"

      - name: Delete Hub/spoke monitor policy definitions
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzPolicyDefinition -ManagementGroupName ${{ env.hubManagementGroup }} | where {$PSItem.Properties.Metadata.source -eq 'https://github.com/Azure/ALZ-Monitor/'} | foreach {Remove-AzPolicyDefinition -Id $PSItem.ResourceId -Force}
          azPSVersion: "latest"

  delete_vwan_job:
    runs-on: ubuntu-latest
    #environment: deploy

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Delete VWAN management group deployments
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzManagementGroupDeployment -ManagementGroupId ${{ env.vwanManagementGroup }} | Remove-AzManagementGroupDeployment -AsJob
          azPSVersion: "latest"

      - name: Az CLI Delete vWAN Network
        id: delete_vwan_network
        shell: bash
        run: |
          az account set --name ${{ env.vwanSubscription }}
          az group delete --name ${{ env.vwanResourceGroup }} --yes
        continue-on-error: true

      - name: Az CLI Delete vwan spoke Network
        id: delete_vwan_spoke_network
        shell: bash
        run: |
          az account set --name ${{ env.vwanSpokeSubscription }}
          az group delete --name ${{ env.vwanSpokeResourceGroup }} --yes
        continue-on-error: true

      - name: Delete VWAN monitor policy assignments
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzPolicyAssignment -Scope /providers/Microsoft.Management/managementGroups/vwan | foreach {Remove-AzPolicyAssignment -Id $PSItem.PolicyAssignmentId}
            Get-AzPolicyAssignment -Scope /providers/Microsoft.Management/managementGroups/vwan-platform-identity | foreach {Remove-AzPolicyAssignment -Id $PSItem.PolicyAssignmentId}
            Get-AzPolicyAssignment -Scope /providers/Microsoft.Management/managementGroups/vwan-platform-connectivity | foreach {Remove-AzPolicyAssignment -Id $PSItem.PolicyAssignmentId}
            Get-AzPolicyAssignment -Scope /providers/Microsoft.Management/managementGroups/vwan-platform-management | foreach {Remove-AzPolicyAssignment -Id $PSItem.PolicyAssignmentId}
            Get-AzPolicyAssignment -Scope /providers/Microsoft.Management/managementGroups/vwan-landingzones | foreach {Remove-AzPolicyAssignment -Id $PSItem.PolicyAssignmentId}
          azPSVersion: "latest"

      - name: Delete VWAN monitor policy Initiatives
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzPolicySetDefinition -ManagementGroupName ${{ env.vwanManagementGroup }} | where {$PSItem.Properties.Metadata.source -eq 'https://github.com/Azure/ALZ-Monitor/'} | foreach {Remove-AzPolicySetDefinition -Id $PSItem.ResourceId -Force}
          azPSVersion: "latest"

      - name: Delete VWAN monitor policy definitions
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzPolicyDefinition -ManagementGroupName ${{ env.vwanManagementGroup }} | where {$PSItem.Properties.Metadata.source -eq 'https://github.com/Azure/ALZ-Monitor/'} | foreach {Remove-AzPolicyDefinition -Id $PSItem.ResourceId -Force}
          azPSVersion: "latest"
