
name: Delete all hub/vwan networking components

# only trigger on pull request closed events
on:
  schedule: 
    - cron: '* 00 * * *'
  workflow_dispatch: {}

permissions:
      id-token: write
      contents: read

env:
  Location: "norwayeast"
  mgSubscriptionId: "6628bab6-9526-4636-a37a-182052d9671c"
  mgResourceGroup: "hubnw-mgmt"
  hubSubscriptionId: "cef889d1-be0e-48d3-ab41-6a15291a2d95"
  hubResourceGroup: "hubnw-connectivity"
  vwanSubscriptionId: "b520e36b-23a2-4c14-a04f-854dc0c24ee1"
  vwanResourceGroup: "vwan-connectivity"

  
jobs:
  deploy_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

    - name: Az CLI Delete Hub Network
      id: delete_hub_network
      shell: bash
      run: |
          az account set --subscription ${{ env.hubSubscriptionId }}
          az group delete --name ${{ env.hubResourceGroup }} --yes
      continue-on-error: true

    - name: Az CLI Delete vWAN Network
      id: delete_hub_network
      shell: bash
      run: |
          az account set --subscription ${{ env.vwanSubscriptionId }}
          az group delete --name ${{ env.vwanResourceGroup }} --yes
      continue-on-error: true

